/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "cv_divisas.h"

bool_t
xdr_entidad (XDR *xdrs, entidad *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->tipo_moneda, 4,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->cantidad, 12,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_CompraVenta (XDR *xdrs, CompraVenta *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_pointer (xdrs, (char **)&objp->sistem, sizeof (entidad), (xdrproc_t) xdr_entidad))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->user, sizeof (entidad), (xdrproc_t) xdr_entidad))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->moneda_compra, 4,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->moneda_pago, 4,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cantidad))
		 return FALSE;
	return TRUE;
}
