/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "cv_divisas.h"


void
cv_divisas_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	struct CompraVenta  compra_divisas_1_arg;
	int  *result_2;
	struct CompraVenta  venta_divisas_1_arg;
	void  *result_3;
	struct CompraVenta  listar_divisas_1_arg;
	void  *result_4;
	struct CompraVenta  listardetalles_divisas_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CV_DIVISAS, CV_DIVISAS_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = compra_divisas_1(&compra_divisas_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = venta_divisas_1(&venta_divisas_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = listar_divisas_1(&listar_divisas_1_arg, clnt);
	if (result_3 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = listardetalles_divisas_1(&listardetalles_divisas_1_arg, clnt);
	if (result_4 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	cv_divisas_1 (host);
exit (0);
}
