/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "cv_divisas.h"
#include "funciones_server.h"

char **
compra_divisas_1_svc(struct CompraVenta *argp, struct svc_req *rqstp)
{
	static char * result;

	char str[3], resultado[1000], resultado2[100];
	int i;

	sprintf(str,"%c",argp->caracter);

	if(strcmp(str,"1")==0){

    //Inicialmente debo rescatar los datos del usuario y del server.
    entidad dinero_servidor[3];  //Creo un vector que me almacene los datos de dinero del servidor
	entidad dinero_usuario[3];	 //Creo un vector que me almacene los datos de dinero del usuario

	FILE * f=fopen("./datos/usuario.txt","a+");
	FILE * f2=fopen("./datos/sistema.txt","a+");	
	rescata_dinero(dinero_servidor,f2);  //Lleno el vector de dinero del servidor con los datos del almacen	
	rescata_dinero(dinero_usuario,f);    //Lleno el vector de dinero del usuario con los datos del almacen	

	
	for(i=0;i<3;i++){
	sprintf(resultado2, "%s %s", dinero_usuario[i].tipo_moneda, dinero_usuario[i].cantidad);	
	strcat(resultado, resultado2);
	strcat(resultado, "\n");
	}

	result = strdup(resultado);
	return &result;
	}



	if(strcmp(str,"2")==0){

    //Inicialmente debo rescatar los datos del usuario y del server.
    entidad dinero_servidor[3];  //Creo un vector que me almacene los datos de dinero del servidor
	entidad dinero_usuario[3];	 //Creo un vector que me almacene los datos de dinero del usuario
	char moneda_compra[4], moneda_pago[4], str[20];
	char * *result_1;
	char resultado[1000];
	int cantidad;
	char *v1, *v2, *v3;

	FILE * f=fopen("./datos/usuario.txt","a+");
	FILE * f2=fopen("./datos/sistema.txt","a+");	
	rescata_dinero(dinero_servidor,f2);  //Lleno el vector de dinero del servidor con los datos del almacen	
	rescata_dinero(dinero_usuario,f);    //Lleno el vector de dinero del usuario con los datos del almacen	

	sprintf(str,"%s",argp->str);         //Recupero el string que envie al server
	v1 = strtok(str, "-");
	v2 = strtok(NULL,"-");
	v3 = strtok(NULL,"-");

	result_1 = div_comprar(dinero_servidor,dinero_usuario,v1,v2,atoi(v3),f,f2);

	sprintf(resultado,"%s", (char *) *result_1);
	
	result = resultado;
	return &result;
	}

return &result;
}


char **
venta_divisas_1_svc(struct CompraVenta *argp, struct svc_req *rqstp)
{
	static char * result;

	char str[3], resultado[1000], resultado2[100];
	int i;

	sprintf(str,"%c",argp->caracter);

	if(strcmp(str,"1")==0){

    //Inicialmente debo rescatar los datos del usuario y del server.
    entidad dinero_servidor[3];  //Creo un vector que me almacene los datos de dinero del servidor
	entidad dinero_usuario[3];	 //Creo un vector que me almacene los datos de dinero del usuario

	FILE * f=fopen("./datos/usuario.txt","a+");
	FILE * f2=fopen("./datos/sistema.txt","a+");	
	rescata_dinero(dinero_servidor,f2);  //Lleno el vector de dinero del servidor con los datos del almacen	
	rescata_dinero(dinero_usuario,f);    //Lleno el vector de dinero del usuario con los datos del almacen	

	
	for(i=0;i<3;i++){
	sprintf(resultado2, "%s %s", dinero_usuario[i].tipo_moneda, dinero_usuario[i].cantidad);	
	strcat(resultado, resultado2);
	strcat(resultado, "\n");
	}

	result = strdup(resultado);
	return &result;
	}

	if(strcmp(str,"2")==0){

    //Inicialmente debo rescatar los datos del usuario y del server.
    entidad dinero_servidor[3];  //Creo un vector que me almacene los datos de dinero del servidor
	entidad dinero_usuario[3];	 //Creo un vector que me almacene los datos de dinero del usuario
	char moneda_venta[4], moneda_pago[4], str[20];
	char * *result_2;
	char resultado[1000];
	int cantidad;
	char *v1, *v2, *v3;

	FILE * f=fopen("./datos/usuario.txt","a+");
	FILE * f2=fopen("./datos/sistema.txt","a+");	
	rescata_dinero(dinero_servidor,f2);  //Lleno el vector de dinero del servidor con los datos del almacen	
	rescata_dinero(dinero_usuario,f);    //Lleno el vector de dinero del usuario con los datos del almacen	

	sprintf(str,"%s",argp->str);         //Recupero el string que envie al server
	v1 = strtok(str, "-");
	v2 = strtok(NULL,"-");
	v3 = strtok(NULL,"-");

	result_2 = div_vender(dinero_servidor,dinero_usuario,v1,v2,atoi(v3),f,f2);

	sprintf(resultado,"%s", (char *) *result_2);
	
	result = resultado;
	return &result;
	}



return &result;
}


char **
listar_divisas_1_svc(int *argp, struct svc_req *rqstp)
{
	//recibe la opcion que puede ser 1,2 o 3
	
	static char * result;
	char ** resultado;
	int a=*argp;
	printf("%i\n",a);
	if(a==1){		//con 1 listaremos los datos del usuario con la funcion listar_datos_usuario
		resultado=listar_datos_usuario();
		printf("1------>%i\n",a);
	}else{
		if(a==2){//con 2 listaremos los datos del sistema con la funcion listar_datos_sistema
			resultado=listar_datos_sistema();
			printf("2------>%i\n",a);
		}else{
			if(a==3){// con 3 llistaremos los cambios de divisas con la funcion imprime_datos_conversion
				resultado=imprime_datos_conversion();
				printf("3-------->%i\n",a);
			}else{
				//strcpy(resultado,"Vuelva a intentarlo!!!\n");
			}
		}
	}
	
	result = *resultado;
	return &result;
}

char **
listardetalles_divisas_1_svc(struct CompraVenta *argp, struct svc_req *rqstp)
{
	static char * result;

	char str[4];
	char op[20];
	char * *result_4;
	char resultado[1000], resultado2[1000];


	sprintf(str,"%s",argp->str);
	result_4 = listar_informacion_moneda(str);
	sprintf(resultado,"%s", (char *) *result_4);
	
	strcat(resultado, "\n\n");

	result_4 = imprime_datos_conversion_filtrado(str);
	sprintf(resultado2,"%s", (char *) *result_4);

	strcat(resultado, resultado2);

	result = resultado;

	return &result;
}
