/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CV_DIVISAS_H_RPCGEN
#define _CV_DIVISAS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct CompraVenta {
	int opcion;
	int entero;
	float flotante;
	double doble;
	char caracter;
	int vector_de_enteros[10];
	char *str;
};
typedef struct CompraVenta CompraVenta;

#define CV_DIVISAS 1
#define CV_DIVISAS_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define compra_divisas 1
extern  char ** compra_divisas_1(struct CompraVenta *, CLIENT *);
extern  char ** compra_divisas_1_svc(struct CompraVenta *, struct svc_req *);
#define venta_divisas 2
extern  char ** venta_divisas_1(struct CompraVenta *, CLIENT *);
extern  char ** venta_divisas_1_svc(struct CompraVenta *, struct svc_req *);
#define listar_divisas 3
extern  char ** listar_divisas_1(int *, CLIENT *);
extern  char ** listar_divisas_1_svc(int *, struct svc_req *);
#define listardetalles_divisas 4
extern  char ** listardetalles_divisas_1(struct CompraVenta *, CLIENT *);
extern  char ** listardetalles_divisas_1_svc(struct CompraVenta *, struct svc_req *);
extern int cv_divisas_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define compra_divisas 1
extern  char ** compra_divisas_1();
extern  char ** compra_divisas_1_svc();
#define venta_divisas 2
extern  char ** venta_divisas_1();
extern  char ** venta_divisas_1_svc();
#define listar_divisas 3
extern  char ** listar_divisas_1();
extern  char ** listar_divisas_1_svc();
#define listardetalles_divisas 4
extern  char ** listardetalles_divisas_1();
extern  char ** listardetalles_divisas_1_svc();
extern int cv_divisas_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_CompraVenta (XDR *, CompraVenta*);

#else /* K&R C */
extern bool_t xdr_CompraVenta ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CV_DIVISAS_H_RPCGEN */
