/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "divisas.h"
#include "funciones_server.h"


char **
comprar_divisas_1_svc(struct EstructuraDatos *argp, struct svc_req *rqstp)
{
	static char * result;

	char str[3];
	printf("hola");
	sprintf(str,"%s",argp->str);

	if(strcmp(str,"1")==0){

    //Inicialmente debo rescatar los datos del usuario y del server.
    entidad dinero_servidor[3];  //Creo un vector que me almacene los datos de dinero del servidor
	entidad dinero_usuario[3];	 //Creo un vector que me almacene los datos de dinero del usuario

	FILE * f=fopen("./datos/usuario.txt","a+");
	FILE * f2=fopen("./datos/sistema.txt","a+");	
	rescata_dinero(dinero_servidor,f2);  //Lleno el vector de dinero del servidor con los datos del almacen	
	rescata_dinero(dinero_usuario,f);    //Lleno el vector de dinero del usuario con los datos del almacen	

	int i;
	char resultado[1000], resultado2[100];
	
	for(i=0;i<3;i++){
	sprintf(resultado2, "%s %s", dinero_usuario[i].tipo_moneda, dinero_usuario[i].cantidad);	
	strcat(resultado, resultado2);
	strcat(resultado, "\n");
	}

	result = strdup(resultado);
	return &result;
	}

return &result;
}

char **
vender_divisas_1_svc(struct EstructuraDatos *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return &result;
}

char **
listar_divisas_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return &result;
}

char **
buscar_info_divisa_1_svc(struct EstructuraDatos *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return &result;
}
