/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DIVISAS_H_RPCGEN
#define _DIVISAS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct EstructuraDatos {
	int opcion;
	int entero;
	float flotante;
	double doble;
	char caracter;
	int vector_de_enteros[10];
	char *str;
};
typedef struct EstructuraDatos EstructuraDatos;

#define DIVISAS 1
#define DIVISAS_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define comprar_divisas 1
extern  char ** comprar_divisas_1(struct EstructuraDatos *, CLIENT *);
extern  char ** comprar_divisas_1_svc(struct EstructuraDatos *, struct svc_req *);
#define vender_divisas 2
extern  char ** vender_divisas_1(struct EstructuraDatos *, CLIENT *);
extern  char ** vender_divisas_1_svc(struct EstructuraDatos *, struct svc_req *);
#define listar_divisas 3
extern  char ** listar_divisas_1(void *, CLIENT *);
extern  char ** listar_divisas_1_svc(void *, struct svc_req *);
#define buscar_info_divisa 4
extern  char ** buscar_info_divisa_1(struct EstructuraDatos *, CLIENT *);
extern  char ** buscar_info_divisa_1_svc(struct EstructuraDatos *, struct svc_req *);
extern int divisas_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define comprar_divisas 1
extern  char ** comprar_divisas_1();
extern  char ** comprar_divisas_1_svc();
#define vender_divisas 2
extern  char ** vender_divisas_1();
extern  char ** vender_divisas_1_svc();
#define listar_divisas 3
extern  char ** listar_divisas_1();
extern  char ** listar_divisas_1_svc();
#define buscar_info_divisa 4
extern  char ** buscar_info_divisa_1();
extern  char ** buscar_info_divisa_1_svc();
extern int divisas_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_EstructuraDatos (XDR *, EstructuraDatos*);

#else /* K&R C */
extern bool_t xdr_EstructuraDatos ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DIVISAS_H_RPCGEN */
