/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "divisas.h"

bool_t
xdr_EstructuraDatos (XDR *xdrs, EstructuraDatos *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_int (xdrs, &objp->opcion))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->entero))
			 return FALSE;
		 if (!xdr_float (xdrs, &objp->flotante))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->doble))
			 return FALSE;
		 if (!xdr_char (xdrs, &objp->caracter))
			 return FALSE;
		buf = XDR_INLINE (xdrs, ( 10 ) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->vector_de_enteros, 10,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;

		} else {
		{
			register int *genp;

			for (i = 0, genp = objp->vector_de_enteros;
				i < 10; ++i) {
				IXDR_PUT_LONG(buf, *genp++);
			}
		}
		}
		 if (!xdr_string (xdrs, &objp->str, ~0))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_int (xdrs, &objp->opcion))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->entero))
			 return FALSE;
		 if (!xdr_float (xdrs, &objp->flotante))
			 return FALSE;
		 if (!xdr_double (xdrs, &objp->doble))
			 return FALSE;
		 if (!xdr_char (xdrs, &objp->caracter))
			 return FALSE;
		buf = XDR_INLINE (xdrs, ( 10 ) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->vector_de_enteros, 10,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;

		} else {
		{
			register int *genp;

			for (i = 0, genp = objp->vector_de_enteros;
				i < 10; ++i) {
				*genp++ = IXDR_GET_LONG(buf);
			}
		}
		}
		 if (!xdr_string (xdrs, &objp->str, ~0))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->opcion))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->entero))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->flotante))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->doble))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->caracter))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->vector_de_enteros, 10,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->str, ~0))
		 return FALSE;
	return TRUE;
}
